globs: ["**/*.md"]
ignores:
  [
    "**/node_modules",
    "**/dist",
    "CLAUDE.md",
    "CLAUDE.sessions.md",
    "cc-sessions",
    "sessions",
    ".claude",
  ]
config:
  default: true
  MD013:
    line_length: 100
