# PR Validation Workflow
#
# Comprehensive validation pipeline for pull requests targeting main branch.
# Runs quality gates, security checks, and compliance validation across multiple Node.js versions.
# This workflow ensures all changes meet production standards before merging.
#
# Triggered on: Pull requests to main branch
# Matrix: Node.js 20.x, 22.x, 24.x (LTS versions, excludes EoS Node.js 18)
# Quality Gates: TypeScript, ESLint, tests, build, security, license compliance

name: PR Validation
on:
  pull_request:
    branches: [main]

permissions:
  contents: read # Repository content access
  actions: read # Access to workflow run data
  checks: write # Post check results and status updates

jobs:
  validate:
    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      # Repository checkout with full history for semantic analysis
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Node.js setup with pnpm caching for optimal performance
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # Enable corepack to install pnpm
      - name: Enable corepack
        run: corepack enable

      # Install dependencies using pnpm with lockfile validation
      - name: Install dependencies
        run: pnpm install

      # TypeScript compilation check without emit
      - name: Type check
        run: pnpm typecheck

      # ESLint + Markdownlint validation for code quality
      - name: Lint
        run: pnpm lint

      # Unit tests execution on all Node.js versions (fast feedback)
      - name: Unit tests
        run: pnpm test:unit

      # Production build validation (required before E2E tests)
      - name: Build
        run: pnpm build

      # Integration tests on Node.js 22.x only (representative coverage)
      - name: Integration tests
        run: pnpm test:integration
        if: matrix.node-version == '22.x'

      # E2E tests on Node.js 22.x only (comprehensive but slow)
      - name: E2E tests
        run: pnpm test:e2e
        if: matrix.node-version == '22.x'

      # Security vulnerability scan using pnpm audit
      - name: Security audit
        run: pnpm audit

      # Enhanced dependency and license review using GitHub's official action
      # Replaces: npm audit signatures + license-checker for comprehensive compliance
      - name: Dependency & License Review
        uses: actions/dependency-review-action@v4
        with:
          vulnerability-check: true
          license-check: true
          fail-on-severity: moderate

      # Package size and content validation
      - name: Package validation
        run: pnpm dlx jsr publish --dry-run --allow-dirty

      # NOTE: Dependency update monitoring removed from PR validation.
      # Dependency updates should be handled in separate scheduled workflows
      # to avoid blocking PR merges for routine maintenance updates.

      # Test coverage reporting with Codecov integration (Node.js 22.x only)
      - name: Coverage check
        run: pnpm test:coverage
        if: matrix.node-version == '22.x'

      - name: Upload coverage reports
        uses: codecov/codecov-action@v4
        if: matrix.node-version == '22.x'
        with:
          file: ./coverage/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
