name: Release

on:
  push:
    branches:
      - main
      - next

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.repository_owner == 'enri3l'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Quality checks
        run: |
          pnpm typecheck
          pnpm lint
          pnpm format

      - name: Build
        run: pnpm build

      - name: Test
        run: |
          pnpm test:run
          pnpm test:integration

      - name: Generate API documentation
        run: pnpm docs:api

      - name: Validate CLI
        run: pnpm docs:validate

      - name: Release
        run: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
